name: Build and Push Docker Images to ACR

on:
  push:
    branches:
      - main

env:
  ACR_NAME: multicontainerappreg.azurecr.io
  FRONTEND_IMAGE: frontend
  BACKEND_IMAGE: backend
  IMAGE_TAG: v1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}
        username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
        password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

    - name: Build and Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.ACR_NAME }}/${{ env.BACKEND_IMAGE }}:${{ env.IMAGE_TAG }}

    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.ACR_NAME }}/${{ env.FRONTEND_IMAGE }}:${{ env.IMAGE_TAG }}
